#!/usr/bin/env python3

import base64

setup = """
IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoKaW1wb3J0IHN1YnByb2Nlc3MKCmRlZiBpbnN0YWxsX2RlcGVuZGVuY2llcygpOgogICAgcHJpbnQoIlxuWypdIEluc3RhbGxpbmcgZGVwZW5kZW5jaWVzLi4uXG4iKQogICAgc3VicHJvY2Vzcy5ydW4oWyJwaXAiLCAiaW5zdGFsbCIsICJyZXF1ZXN0cyIsICJiZWF1dGlmdWxzb3VwNCIsICJ0cWRtIiwgImNvbG9yYW1hIl0pCgpkZWYgbWFpbigpOgogICAgaW5zdGFsbF9kZXBlbmRlbmNpZXMoKQogICAgcHJpbnQoIlxuWypdIFNldHVwIGNvbXBsZXRlISIpCiAgICBwcmludCgiTm93IFJ1bjogcHl0aG9uMyB3ZWJfc2NyYXAucHkiKQoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIG1haW4oKQ==
"""

decoded_script = base64.b64decode(setup).decode('utf-8')

exec(decoded_script)
